defmodule TamayotchiStack.Features.Backups do
  @moduledoc false

  alias TamayotchiStack.Manifest
  alias TamayotchiStack.Project

  @marker "# Generated by tamayotchi_stack backups; owned by your application."
  @secret_names ~w(LITESTREAM_ENDPOINT LITESTREAM_ACCESS_KEY_ID LITESTREAM_SECRET_ACCESS_KEY)
  @files [
    {"rel/overlays/etc/litestream.yml", "litestream.yml.eex"},
    {"rel/overlays/etc/backup.cron", "backup.cron.eex"},
    {"rel/overlays/bin/backup-env", "backup-env.eex"},
    {"rel/overlays/bin/litestream-backup", "litestream-backup.eex"},
    {"rel/overlays/bin/litestream-restore", "litestream-restore.eex"},
    {"rel/overlays/bin/litestream-list", "litestream-list.eex"},
    {"docs/sqlite-backups.md", "README.md.eex"}
  ]

  def paths, do: Enum.map(@files, &elem(&1, 0))

  def configure(igniter, app, false, _kamal?) do
    igniter = Manifest.set_feature(igniter, app, :backups, false)

    if Igniter.exists?(igniter, "rel/overlays/etc/backup.cron") do
      Igniter.add_notice(
        igniter,
        "--no-backups stops management, not an existing backup schedule. Stop the Kamal backup role explicitly to disable scheduled backups; no backups or credentials were deleted."
      )
    else
      igniter
    end
  end

  def configure(igniter, app, true, kamal?) do
    if kamal? and Project.phoenix?(igniter) and Project.sqlite?(igniter) do
      bindings = [app: to_string(app), slug: app |> to_string() |> String.replace("_", "-")]

      Enum.reduce(@files, igniter, fn {path, template}, igniter ->
        put_owned_file(igniter, path, render(template, bindings))
      end)
      |> patch("Dockerfile", &dockerfile(&1, bindings))
      |> patch("config/deploy.yml", &deployment(&1, bindings))
      |> patch(".kamal/secrets", &secrets/1)
      |> Manifest.set_feature(app, :backups, true)
      |> Igniter.add_notice("""
      SQLite backups: daily at 15:00 UTC in the Kamal backup role, with seven-day retention.
      Create a PRIVATE #{bindings[:slug]}-db-backups bucket and a bucket-scoped token.
      Add LITESTREAM_ENDPOINT, LITESTREAM_ACCESS_KEY_ID, and LITESTREAM_SECRET_ACCESS_KEY
      to your deployment's 1Password item. These are separate from application R2 storage.
      Deploy, run kamal backup, then kamal backup-restore to verify recovery to a separate file.
      Read docs/sqlite-backups.md for recovery, monitoring, schedule changes, and S3 settings.
      Daily backups can lose changes since the last successful run; monitor job completion.
      """)
    else
      Igniter.add_issue(
        igniter,
        "--backups requires a Phoenix SQLite project and --kamal; enable those features or use --no-backups"
      )
    end
  end

  defp put_owned_file(igniter, path, desired) do
    Igniter.create_or_update_file(igniter, path, desired, fn source ->
      current = Rewrite.Source.get(source, :content)

      if current == desired or String.starts_with?(current, @marker <> "\n") or
           String.starts_with?(current, "#!/bin/sh\n" <> @marker <> "\n") do
        source
      else
        {:error,
         "Refusing to overwrite unmanaged #{path}; reconcile your backup implementation manually"}
      end
    end)
  end

  defp patch(igniter, path, updater) do
    Igniter.update_file(igniter, path, fn source ->
      current = Rewrite.Source.get(source, :content)

      if String.starts_with?(current, "# Managed by tamayotchi_stack.\n") do
        case updater.(current) do
          {:ok, updated} -> Rewrite.Source.update(source, :content, updated)
          {:error, reason} -> {:error, "Cannot safely add SQLite backups to #{path}: #{reason}"}
        end
      else
        {:error,
         "Refusing to modify unmanaged #{path}; adopt your deployment manually before enabling backups"}
      end
    end)
  end

  defp dockerfile(current, bindings) do
    with :absent <- block_status(current, "docker") do
      if length(Regex.scan(~r/^FROM /m, current)) == 2 and
           String.contains?(current, "FROM ${RUNNER_IMAGE} AS final\n") and
           length(Regex.scan(~r/^USER nobody$/m, current)) == 1 and
           not Regex.match?(~r/litestream|supercronic/i, current) do
        {:ok,
         String.replace(
           current,
           "USER nobody\n",
           block("docker", render("docker.eex", bindings)) <> "USER nobody\n",
           global: false
         )}
      else
        {:error,
         "install the pinned Litestream/Supercronic binaries in the final root stage manually (see the backups Docker template)"}
      end
    else
      :present -> {:ok, current}
      error -> error
    end
  end

  defp deployment(current, bindings) do
    with :ok <- validate_layout(current),
         {:ok, current} <- section(current, "servers", &role/1),
         {:ok, current} <- section(current, "env", &environment(&1, bindings)),
         {:ok, current} <- section(current, "aliases", &aliases(&1, bindings)) do
      {:ok, current}
    end
  end

  defp validate_layout(current) do
    if Regex.match?(~r/^  arch: amd64\s*$/m, current) and
         Regex.match?(
           ~r/^    DATABASE_PATH: ["']?\/app\/storage\/[A-Za-z0-9_.-]+["']?\s*$/m,
           current
         ) and
         Regex.match?(~r/^  - ["']?[A-Za-z0-9_.-]+:\/app\/storage["']?\s*$/m, current) do
      :ok
    else
      {:error,
       "expected amd64 with DATABASE_PATH on a named shared /app/storage volume; adopt custom storage/architecture layouts manually"}
    end
  end

  defp role(servers) do
    with :absent <- block_status(servers, "role") do
      hosts = Regex.scan(~r/^\s+- ([A-Za-z0-9.-]+)\s*$/m, servers)
      roles = Regex.scan(~r/^  ([a-zA-Z_][a-zA-Z_0-9-]*):/m, servers)

      if roles == [["  web:", "web"]] and length(hosts) == 1 do
        [[_, host]] = hosts

        role = """
          backup:
            hosts:
              - #{host}
            proxy: false
            cmd: "/usr/local/bin/supercronic /app/etc/backup.cron"
            env:
              clear:
                TZ: UTC
        """

        {:ok, servers <> block("role", role, "  ")}
      else
        {:error,
         "backups require one web host sharing the SQLite volume; configure the backup role manually for custom/multi-host deployments"}
      end
    else
      :present -> {:ok, servers}
      error -> error
    end
  end

  defp environment(env, bindings) do
    case {block_status(env, "clear"), block_status(env, "secret")} do
      {:present, :present} ->
        {:ok, env}

      {:absent, :absent} ->
        pattern = ~r/\A(  clear:\n)(.*?)(  secret:\n)(.*)\z/s

        case Regex.run(pattern, env) do
          [_, clear_start, clear, secret_start, secret] ->
            if String.contains?(env, "LITESTREAM_") or not simple_env?(clear, secret) do
              {:error,
               "existing Litestream settings or a custom env structure need manual reconciliation"}
            else
              clear_additions =
                "    LITESTREAM_BUCKET_NAME: #{bindings[:slug]}-db-backups\n    LITESTREAM_BUCKET_PATH: #{bindings[:slug]}-production-v0.5\n    LITESTREAM_REGION: auto\n"

              secret_additions = Enum.map_join(@secret_names, "", &"    - #{&1}\n")

              {:ok,
               clear_start <>
                 clear <>
                 block("clear", clear_additions, "    ") <>
                 secret_start <> secret <> block("secret", secret_additions, "    ")}
            end

          _ ->
            {:error,
             "expected env.clear and env.secret sections; add the Litestream environment references manually"}
        end

      _ ->
        {:error, "incomplete backup environment markers; repair both clear and secret sections"}
    end
  end

  defp simple_env?(clear, secret) do
    Enum.all?(
      String.split(clear, "\n"),
      &Regex.match?(~r/^(\s*|\s*#.*|    ["']?[A-Za-z_][A-Za-z_0-9]*["']?:.*)$/, &1)
    ) and
      Enum.all?(String.split(secret, "\n"), &Regex.match?(~r/^(\s*|\s*#.*|    - .*)$/, &1))
  end

  defp aliases(aliases, bindings) do
    with :absent <- block_status(aliases, "aliases") do
      if Regex.match?(~r/^  backup(?:[-\w]*):/m, aliases) do
        {:error, "backup aliases already exist; reconcile them manually"}
      else
        additions = """
          backup: app exec --reuse --roles backup "/app/bin/litestream-backup"
          backup-logs: app logs --roles backup --lines 100
          backup-list: app exec --reuse --roles backup "/app/bin/litestream-list"
          backup-restore: app exec --reuse --roles backup "/app/bin/litestream-restore /app/storage/#{bindings[:app]}-restored.db"
        """

        {:ok, aliases <> block("aliases", additions, "  ")}
      end
    else
      :present -> {:ok, aliases}
      error -> error
    end
  end

  defp secrets(current) do
    with :absent <- block_status(current, "credentials") do
      case Regex.run(~r/^SECRETS=\$\(kamal secrets fetch [^\n]*\)$/m, current) do
        [fetch] ->
          if Enum.any?(@secret_names, &String.contains?(current, &1)) do
            {:error,
             "Litestream secret references already exist; reconcile the credentials block manually"}
          else
            # A separate fetch leaves the application's existing secret provider command intact.
            backup_fetch = String.replace_prefix(fetch, "SECRETS=", "BACKUP_SECRETS=")

            prefix =
              Regex.replace(
                ~r/ KAMAL_REGISTRY_PASSWORD.*\)$/,
                backup_fetch,
                " " <> Enum.join(@secret_names, " ") <> ")"
              )

            if prefix == backup_fetch do
              {:error,
               "expected the standard 1Password fetch command; add the backup secret references manually"}
            else
              extracts =
                Enum.map_join(
                  @secret_names,
                  "",
                  &"#{&1}=$(kamal secrets extract #{&1} $BACKUP_SECRETS)\n"
                )

              {:ok,
               String.replace(
                 current,
                 fetch,
                 fetch <> "\n" <> block("credentials", prefix <> "\n" <> extracts),
                 global: false
               )}
            end
          end

        _ ->
          {:error,
           "expected a single-line Kamal secrets fetch; add backup references to your provider manually"}
      end
    else
      :present -> {:ok, current}
      error -> error
    end
  end

  defp section(current, key, updater) do
    pattern = Regex.compile!("^#{key}:\\n(.*?)(?=^[^ \\n#]|\\z)", "ms")

    case Regex.scan(pattern, current) do
      [[whole, body]] ->
        case updater.(body) do
          {:ok, updated} ->
            {:ok, String.replace(current, whole, key <> ":\n" <> updated, global: false)}

          error ->
            error
        end

      _ ->
        {:error, "expected exactly one #{key} section"}
    end
  end

  defp block(name, content, indent \\ "") do
    "#{indent}# tamayotchi_stack backups:#{name} begin\n" <>
      content <> "#{indent}# tamayotchi_stack backups:#{name} end\n"
  end

  defp block_status(content, name) do
    first =
      length(
        Regex.scan(Regex.compile!("^ *# tamayotchi_stack backups:#{name} begin$", "m"), content)
      )

    last =
      length(
        Regex.scan(Regex.compile!("^ *# tamayotchi_stack backups:#{name} end$", "m"), content)
      )

    case {first, last} do
      {0, 0} ->
        :absent

      {1, 1} ->
        if Regex.match?(
             Regex.compile!(
               "# tamayotchi_stack backups:#{name} begin\\n.*# tamayotchi_stack backups:#{name} end",
               "s"
             ),
             content
           ),
           do: :present,
           else: {:error, "reversed backups:#{name} markers; repair them manually"}

      _ ->
        {:error, "incomplete or duplicate backups:#{name} markers; repair them manually"}
    end
  end

  defp render(template, bindings) do
    :tamayotchi_stack
    |> :code.priv_dir()
    |> Path.join("templates/backups/#{template}")
    |> EEx.eval_file(bindings)
  end
end
