defmodule TamayotchiStack.Features.Backups do
  @moduledoc false

  alias TamayotchiStack.Manifest

  @marker "# Generated by tamayotchi_stack backups; owned by your application."
  @secret_names ~w(LITESTREAM_ENDPOINT LITESTREAM_ACCESS_KEY_ID LITESTREAM_SECRET_ACCESS_KEY)
  @files [
    {"rel/overlays/etc/litestream.yml", "litestream.yml.eex"},
    {"rel/overlays/etc/backup.cron", "backup.cron.eex"},
    {"rel/overlays/bin/backup-env", "backup-env.eex"},
    {"rel/overlays/bin/litestream-backup", "litestream-backup.eex"},
    {"rel/overlays/bin/litestream-restore", "litestream-restore.eex"},
    {"rel/overlays/bin/litestream-list", "litestream-list.eex"},
    {"docs/sqlite-backups.md", "README.md.eex"}
  ]

  def paths, do: Enum.map(@files, &elem(&1, 0))

  @doc false
  def credentials_scoped?(deployment) do
    with [_, servers] <- Regex.run(~r/^servers:\n(.*?)(?=^\S|\z)/ms, deployment),
         [_, role] <- Regex.run(~r/^  backup:\n(.*?)(?=^  \S|\z)/ms, servers),
         [_, env] <- Regex.run(~r/^env:\n(.*?)(?=^\S|\z)/ms, deployment),
         {:ok, _} <- ensure_no_global_credentials(env) do
      scoped_credentials?(role)
    else
      _ -> false
    end
  end

  def configure(igniter, app, true), do: configure_sqlite(igniter, app)

  def configure(igniter, app, false) do
    igniter = Manifest.set_feature(igniter, app, :backups, false)

    if Igniter.exists?(igniter, "rel/overlays/etc/backup.cron") do
      Igniter.add_notice(
        igniter,
        "Phoenix is not managed. Existing backup files and deployed schedules were preserved; review them manually. No backups or credentials were deleted."
      )
    else
      igniter
    end
  end

  defp configure_sqlite(igniter, app) do
    bindings = [app: to_string(app), slug: app |> to_string() |> String.replace("_", "-")]

    Enum.reduce(@files, igniter, fn {path, template}, igniter ->
      put_owned_file(igniter, path, render(template, bindings))
    end)
    |> configure_kamal(bindings)
    |> Manifest.set_feature(app, :backups, true)
    |> Igniter.add_notice("""
    SQLite detected: backup files are always included, with seven-day retention.
    Setup/install automatically provision the PRIVATE #{bindings[:slug]}-db-backups bucket
    and separate Litestream credentials using your one-time 1Password bootstrap item.
    With --no-secrets, run mix tamayotchi.secrets later or provision/import manually.
    Sync only maintains files; it never creates credentials or cloud resources.
    Deploy and run kamal backup, then kamal backup-restore to verify recovery.
    Phoenix includes SQLite, Kamal, and the backup role automatically.
    Read docs/sqlite-backups.md for recovery, monitoring, schedule changes, and S3 settings.
    Daily backups can lose changes since the last successful run; monitor job completion.
    """)
  end

  defp configure_kamal(igniter, bindings) do
    igniter
    |> patch("Dockerfile", &dockerfile(&1, bindings))
    |> patch("config/deploy.yml", &deployment(&1, bindings))
    |> patch(".kamal/secrets", &secrets/1)
    |> Igniter.add_notice(
      "Kamal backup role configured for 15:00 UTC daily, with role-scoped credentials. Deploy it and verify a backup/restore before relying on the schedule."
    )
  end

  defp put_owned_file(igniter, path, desired) do
    Igniter.create_or_update_file(igniter, path, desired, fn source ->
      current = Rewrite.Source.get(source, :content)

      if current == desired or String.starts_with?(current, @marker <> "\n") or
           String.starts_with?(current, "#!/bin/sh\n" <> @marker <> "\n") do
        source
      else
        {:error,
         "Refusing to overwrite unmanaged #{path}; reconcile your backup implementation manually"}
      end
    end)
  end

  defp patch(igniter, path, updater) do
    Igniter.update_file(igniter, path, fn source ->
      current = Rewrite.Source.get(source, :content)

      if String.starts_with?(current, "# Managed by tamayotchi_stack.\n") do
        case updater.(current) do
          {:ok, updated} -> Rewrite.Source.update(source, :content, updated)
          {:error, reason} -> {:error, "Cannot safely add SQLite backups to #{path}: #{reason}"}
        end
      else
        {:error,
         "Refusing to modify unmanaged #{path}; adopt your deployment manually before enabling backups"}
      end
    end)
  end

  defp dockerfile(current, bindings) do
    with :absent <- block_status(current, "docker") do
      if length(Regex.scan(~r/^FROM /m, current)) == 2 and
           String.contains?(current, "FROM ${RUNNER_IMAGE} AS final\n") and
           length(Regex.scan(~r/^USER nobody$/m, current)) == 1 and
           not Regex.match?(~r/litestream|supercronic/i, current) do
        {:ok,
         String.replace(
           current,
           "USER nobody\n",
           block("docker", render("docker.eex", bindings)) <> "USER nobody\n",
           global: false
         )}
      else
        {:error,
         "install the pinned Litestream/Supercronic binaries in the final root stage manually (see the backups Docker template)"}
      end
    else
      :present -> {:ok, current}
      error -> error
    end
  end

  defp deployment(current, bindings) do
    with :ok <- validate_layout(current),
         {:ok, current} <- section(current, "servers", &role/1),
         {:ok, current} <- section(current, "env", &environment(&1, bindings)),
         {:ok, current} <- section(current, "aliases", &aliases(&1, bindings)) do
      {:ok, current}
    end
  end

  defp validate_layout(current) do
    if Regex.match?(~r/^  arch: amd64\s*$/m, current) and
         Regex.match?(
           ~r/^    DATABASE_PATH: ["']?\/app\/storage\/[A-Za-z0-9_.-]+["']?\s*$/m,
           current
         ) and
         Regex.match?(~r/^  - ["']?[A-Za-z0-9_.-]+:\/app\/storage["']?\s*$/m, current) do
      :ok
    else
      {:error,
       "expected amd64 with DATABASE_PATH on a named shared /app/storage volume; adopt custom storage/architecture layouts manually"}
    end
  end

  defp role(servers) do
    with :absent <- block_status(servers, "role") do
      hosts = Regex.scan(~r/^\s+- ([A-Za-z0-9.-]+)\s*$/m, servers)
      roles = Regex.scan(~r/^  ([a-zA-Z_][a-zA-Z_0-9-]*):/m, servers)

      if roles == [["  web:", "web"]] and length(hosts) == 1 do
        [[_, host]] = hosts

        role = """
          backup:
            hosts:
              - #{host}
            proxy: false
            cmd: "/usr/local/bin/supercronic /app/etc/backup.cron"
            env:
              clear:
                TZ: UTC
              secret:
                - LITESTREAM_ENDPOINT
                - LITESTREAM_ACCESS_KEY_ID
                - LITESTREAM_SECRET_ACCESS_KEY
        """

        {:ok, servers <> block("role", role, "  ")}
      else
        {:error,
         "backups require one web host sharing the SQLite volume; configure the backup role manually for custom/multi-host deployments"}
      end
    else
      :present -> ensure_role_secrets(servers)
      error -> error
    end
  end

  defp ensure_role_secrets(servers) do
    pattern =
      ~r/(  # tamayotchi_stack backups:role begin\n)(.*?)(  # tamayotchi_stack backups:role end\n)/s

    case Regex.run(pattern, servers) do
      [whole, start, role, finish] ->
        cond do
          scoped_credentials?(role) ->
            {:ok, servers}

          not String.contains?(role, "LITESTREAM_") and
            length(Regex.scan(~r/^    env:$/m, role)) == 1 and
            not Regex.match?(~r/^      secret:/m, role) and
              Regex.match?(
                ~r/^    env:\n      clear:\n(?:        [A-Za-z_][A-Za-z_0-9]*:[^\n]*\n| *#[^\n]*\n|\n)*\z/m,
                role
              ) ->
            secret = "      secret:\n" <> Enum.map_join(@secret_names, "", &"        - #{&1}\n")

            {:ok,
             String.replace(servers, whole, start <> role <> secret <> finish, global: false)}

          true ->
            {:error,
             "move all three Litestream credentials into backup.env.secret manually; refusing to rewrite a customized backup role"}
        end

      _ ->
        {:error, "cannot safely identify the backup role's credential scope"}
    end
  end

  defp scoped_credentials?(role) do
    with [[_, env]] <- Regex.scan(~r/^    env:\n(.*?)(?=^    \S|\z)/ms, role),
         [[_, secret]] <- Regex.scan(~r/^      secret:\n(.*?)(?=^      \S|\z)/ms, env) do
      Enum.all?(@secret_names, &Regex.match?(Regex.compile!("^        - #{&1}$", "m"), secret))
    else
      _ -> false
    end
  end

  defp environment(env, bindings) do
    case {block_status(env, "clear"), block_status(env, "secret")} do
      {:present, :present} ->
        # Migrate only the exact old generated credential block. Never remove a
        # customized block or leave backup credentials available to the web role.
        legacy = block("secret", Enum.map_join(@secret_names, "", &"    - #{&1}\n"), "    ")

        if String.contains?(env, legacy) do
          ensure_no_global_credentials(String.replace(env, legacy, "", global: false))
        else
          {:error,
           "move Litestream credentials out of global env.secret into backup.env.secret; the legacy block has custom changes"}
        end

      {:present, :absent} ->
        ensure_no_global_credentials(env)

      {:absent, :absent} ->
        pattern = ~r/\A(  clear:\n)(.*?)(  secret:\n)(.*)\z/s

        case Regex.run(pattern, env) do
          [_, clear_start, clear, secret_start, secret] ->
            if String.contains?(env, "LITESTREAM_") or not simple_env?(clear, secret) do
              {:error,
               "existing Litestream settings or a custom env structure need manual reconciliation"}
            else
              clear_additions =
                "    LITESTREAM_BUCKET_NAME: #{bindings[:slug]}-db-backups\n    LITESTREAM_BUCKET_PATH: #{bindings[:slug]}-production-v0.5\n    LITESTREAM_REGION: auto\n"

              {:ok,
               clear_start <>
                 clear <>
                 block("clear", clear_additions, "    ") <>
                 secret_start <> secret}
            end

          _ ->
            {:error,
             "expected env.clear and env.secret sections; add the Litestream environment references manually"}
        end

      _ ->
        {:error, "incomplete backup environment markers; repair both clear and secret sections"}
    end
  end

  defp ensure_no_global_credentials(env) do
    if Enum.any?(@secret_names, &String.contains?(env, &1)),
      do:
        {:error,
         "Litestream credentials must be scoped to backup.env.secret, not the web/global environment"},
      else: {:ok, env}
  end

  defp simple_env?(clear, secret) do
    Enum.all?(
      String.split(clear, "\n"),
      &Regex.match?(~r/^(\s*|\s*#.*|    ["']?[A-Za-z_][A-Za-z_0-9]*["']?:.*)$/, &1)
    ) and
      Enum.all?(String.split(secret, "\n"), &Regex.match?(~r/^(\s*|\s*#.*|    - .*)$/, &1))
  end

  defp aliases(aliases, bindings) do
    with :absent <- block_status(aliases, "aliases") do
      if Regex.match?(~r/^  backup(?:[-\w]*):/m, aliases) do
        {:error, "backup aliases already exist; reconcile them manually"}
      else
        additions = """
          backup: app exec --reuse --roles backup "/app/bin/litestream-backup"
          backup-logs: app logs --roles backup --lines 100
          backup-list: app exec --reuse --roles backup "/app/bin/litestream-list"
          backup-restore: app exec --reuse --roles backup "/app/bin/litestream-restore /app/storage/#{bindings[:app]}-restored.db"
        """

        {:ok, aliases <> block("aliases", additions, "  ")}
      end
    else
      :present -> {:ok, aliases}
      error -> error
    end
  end

  defp secrets(current) do
    with :absent <- block_status(current, "credentials") do
      case Regex.run(~r/^SECRETS=\$\(kamal secrets fetch [^\n]*\)$/m, current) do
        [fetch] ->
          if Enum.any?(@secret_names, &String.contains?(current, &1)) do
            {:error,
             "Litestream secret references already exist; reconcile the credentials block manually"}
          else
            # A separate fetch leaves the application's existing secret provider command intact.
            backup_fetch = String.replace_prefix(fetch, "SECRETS=", "BACKUP_SECRETS=")

            prefix =
              Regex.replace(
                ~r/ KAMAL_REGISTRY_PASSWORD.*\)$/,
                backup_fetch,
                " " <> Enum.join(@secret_names, " ") <> ")"
              )

            if prefix == backup_fetch do
              {:error,
               "expected the standard 1Password fetch command; add the backup secret references manually"}
            else
              extracts =
                Enum.map_join(
                  @secret_names,
                  "",
                  &"#{&1}=$(kamal secrets extract #{&1} $BACKUP_SECRETS)\n"
                )

              {:ok,
               String.replace(
                 current,
                 fetch,
                 fetch <> "\n" <> block("credentials", prefix <> "\n" <> extracts),
                 global: false
               )}
            end
          end

        _ ->
          {:error,
           "expected a single-line Kamal secrets fetch; add backup references to your provider manually"}
      end
    else
      :present -> {:ok, current}
      error -> error
    end
  end

  defp section(current, key, updater) do
    pattern = Regex.compile!("^#{key}:\\n(.*?)(?=^[^ \\n#]|\\z)", "ms")

    case Regex.scan(pattern, current) do
      [[whole, body]] ->
        case updater.(body) do
          {:ok, updated} ->
            {:ok, String.replace(current, whole, key <> ":\n" <> updated, global: false)}

          error ->
            error
        end

      _ ->
        {:error, "expected exactly one #{key} section"}
    end
  end

  defp block(name, content, indent \\ "") do
    "#{indent}# tamayotchi_stack backups:#{name} begin\n" <>
      content <> "#{indent}# tamayotchi_stack backups:#{name} end\n"
  end

  defp block_status(content, name) do
    first =
      length(
        Regex.scan(Regex.compile!("^ *# tamayotchi_stack backups:#{name} begin$", "m"), content)
      )

    last =
      length(
        Regex.scan(Regex.compile!("^ *# tamayotchi_stack backups:#{name} end$", "m"), content)
      )

    case {first, last} do
      {0, 0} ->
        :absent

      {1, 1} ->
        if Regex.match?(
             Regex.compile!(
               "# tamayotchi_stack backups:#{name} begin\\n.*# tamayotchi_stack backups:#{name} end",
               "s"
             ),
             content
           ),
           do: :present,
           else: {:error, "reversed backups:#{name} markers; repair them manually"}

      _ ->
        {:error, "incomplete or duplicate backups:#{name} markers; repair them manually"}
    end
  end

  defp render(template, bindings) do
    :tamayotchi_stack
    |> :code.priv_dir()
    |> Path.join("templates/backups/#{template}")
    |> EEx.eval_file(bindings)
  end
end
