defmodule TamayotchiStack.Features.R2 do
  @moduledoc false

  alias TamayotchiStack.Manifest

  @marker "# Generated by tamayotchi_stack R2; owned by your application."
  @dependencies [
    ex_aws: "~> 2.7",
    ex_aws_s3: "~> 2.5",
    req: "~> 0.5",
    jason: "~> 1.4",
    sweet_xml: "~> 0.7"
  ]

  def bucket_for_app(app) do
    slug = app |> to_string() |> String.replace("_", "-")
    if byte_size(slug) < 3, do: slug <> "-storage", else: slug
  end

  def configure(igniter, app, false), do: Manifest.set_feature(igniter, app, :r2, false)

  def configure(igniter, app, true) do
    base = Igniter.Project.Module.module_name_prefix(igniter)
    bindings = [app: inspect(app), base: inspect(base)]
    directory = base |> Module.split() |> Enum.map_join("/", &Macro.underscore/1)

    igniter =
      Enum.reduce(@dependencies, igniter, fn dep, igniter ->
        Igniter.Project.Deps.add_dep(igniter, dep, on_exists: :skip, error?: true)
      end)

    [
      {"lib/#{directory}/storage.ex", "storage.ex.eex"},
      {"lib/#{directory}/storage/r2.ex", "r2.ex.eex"},
      {"lib/#{directory}/storage/fake.ex", "fake.ex.eex"},
      {"test/#{directory}/storage_test.exs", "storage_test.exs.eex"},
      {"test/#{directory}/storage/r2_test.exs", "r2_test.exs.eex"}
    ]
    |> Enum.reduce(igniter, fn {path, template}, igniter ->
      put_owned_file(igniter, path, render(template, bindings))
    end)
    |> configure_runtime(app, render("config.exs.eex", bindings))
    |> Manifest.set_feature(app, :r2, true)
    |> Igniter.add_notice("""
    R2 storage is app-owned. Run mix deps.get after accepting these changes.
    Before production deployment:
    - Setup/install automatically create the bucket and bucket-scoped credentials
      using your one-time 1Password bootstrap item, unless --no-secrets was chosen.
    - For file-only setup or custom providers, run mix tamayotchi.secrets afterward
      or import matching credentials with --no-provision. Never commit credentials.
    - Supply R2_BUCKET and the saved R2_* credentials to your production environment.
    - R2_REGION defaults to auto. R2_PUBLIC_BASE_URL is optional; configure public
      access/custom domain and DNS yourself if you need public URLs.
    - Kamal fetches the R2 fields from the application's 1Password item.
    Tests and development without credentials use Storage.Fake (no persistent uploads).
    Replace the :storage adapter to use another backend; sync preserves app-owned edits.
    --no-r2 stops managing the feature; it does not delete storage code or configuration.
    """)
  end

  # App-owned edits are preserved, even when the file carries our marker.
  defp put_owned_file(igniter, path, desired) do
    Igniter.create_or_update_file(igniter, path, desired, fn source ->
      current = Rewrite.Source.get(source, :content)

      if current == desired or String.starts_with?(current, @marker) do
        source
      else
        {:error,
         "Refusing to overwrite unmanaged #{path}; integrate the storage contract manually, " <>
           "then add #{@marker} only if it is compatible"}
      end
    end)
  end

  defp configure_runtime(igniter, app, desired) do
    Igniter.create_or_update_elixir_file(igniter, "config/runtime.exs", desired, fn zipper ->
      case Igniter.Code.Common.move_to_cursor_match_in_scope(
             zipper,
             "tamayotchi_r2_storage = __cursor__()"
           ) do
        {:ok, _} ->
          {:ok, zipper}

        :error ->
          if Igniter.Project.Config.configures_key?(zipper, app, :storage) do
            {:error,
             "Existing :storage runtime configuration conflicts with R2; integrate the R2 runtime template manually"}
          else
            {:ok, Igniter.Code.Common.add_code(zipper, desired)}
          end
      end
    end)
  end

  defp render(template, bindings) do
    :tamayotchi_stack
    |> :code.priv_dir()
    |> Path.join("templates/r2/#{template}")
    |> EEx.eval_file(bindings)
  end
end
